spring:
  application:
    name: configdemo

  config:   #import configuration from config server
    import: configserver:http://localhost:8888

  profiles:
    active: prod

build:
  id: ${FROM_ENV}
  version: ${FROM_ENV}
  name: ${FROM_ENV}

