spring:
  application:
    name: configdemo

  config:   #import configuration from config server
    import: configserver:http://localhost:8888

  profiles:
    active: prod

build:
  id: ${FROM_ENV}
  version: ${FROM_ENV}
  name: ${FROM_ENV}

#Actuator   (to use refresh scope)
management:
  endpoints:
    web:
      exposure:
        include: busrefresh  #to make use of spring-cloud-starter-bus-amqp (Refreshes all instances (broadcast over the bus) we need to hit POST on atleast one microservice not all)
        #http://localhost:8080/actuator/busrefresh

#manually need to make POST call to get dynamic config - http://localhost:8080/actuator/refresh - (Only refreshes the instance you call it on)

#encrypt:
#  key: myEncryptionKey123    #to encrypt and decrypt configuration values