spring:
  application:
    name: configdemo

  config:   #import configuration from config server
    import: configserver:http://localhost:8888

  profiles:
    active: prod

build:
  id: ${FROM_ENV}
  version: ${FROM_ENV}
  name: ${FROM_ENV}

#Actuator   (to use refresh scope)
management:
  endpoints:
    web:
      exposure:
        include: refresh

#encrypt:
#  key: myEncryptionKey123    #to encrypt and decrypt configuration values